@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}

@category_general = general

# Some random ID I know is in the DB
@example_fortune_uuid = 634c50fb143c1fb0e268e869

###
POST http://{{host}}/fortunes HTTP/1.1 
content-type: application/json

{
    "category": "general",
    "fortune": "You will live another day."
}

###
GET http://{{host}}/fortunes HTTP/1.1

###
GET http://{{host}}/fortunes/{{category_general}} HTTP/1.1

###
GET http://{{host}}/fortune/{{example_fortune_uuid}} HTTP/1.1

###
GET http://{{host}}/randomFortune/general HTTP/1.1


###

PUT http://{{host}}/fortune/{{example_fortune_uuid}} HTTP/1.1
content-type: application/json

{
    "category": "general",
    "fortune": "You will not live another day."
}

###
DELETE http://{{host}}/fortune/{{example_fortune_uuid}} HTTP/1.1
